name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        while IFS= read -r package
        do
            sudo apt-get install -y "$package"
        done < system-requirements.txt

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build binary
      run: pyinstaller --onefile gotify_gnome_desktop.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gotify_gnome_desktop
        path: dist/*
